language: cpp
sudo: false

env:
  global:
    # limit parallel threads (default is 32!)
    - OMP_NUM_THREADS=4
    - STXXL_TMPDIR=/tmp

matrix:
  # gcc-4.8 builds
  include:
    - env: CMAKE_CC="gcc-4.8" CMAKE_CXX="g++-4.8" CMAKE_FLAGS=""     CMAKE_ARGS="-DCMAKE_BUILD_TYPE=RelWithAssert   -DUSE_OPENMP=ON   -DUSE_GNU_PARALLEL=OFF"
      addons: &gcc48
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8
    - env: CMAKE_CC="gcc-4.8" CMAKE_CXX="g++-4.8" CMAKE_FLAGS=""     CMAKE_ARGS="-DCMAKE_BUILD_TYPE=RelWithAssert   -DUSE_OPENMP=ON   -DUSE_GNU_PARALLEL=ON"
      addons: *gcc48
    - env: CMAKE_CC="gcc-4.8" CMAKE_CXX="g++-4.8" CMAKE_FLAGS=""     CMAKE_ARGS="-DCMAKE_BUILD_TYPE=Release -DUSE_OPENMP=ON   -DUSE_GNU_PARALLEL=OFF"
      addons: *gcc48
    - env: CMAKE_CC="gcc-4.8" CMAKE_CXX="g++-4.8" CMAKE_FLAGS=""     CMAKE_ARGS="-DCMAKE_BUILD_TYPE=Release -DUSE_OPENMP=ON   -DUSE_GNU_PARALLEL=ON"
      addons: *gcc48
      # one 32-bit build
    - env: CMAKE_CC="gcc-4.8"     CMAKE_CXX="g++-4.8"     CMAKE_FLAGS="-m32" CMAKE_ARGS="-DCMAKE_BUILD_TYPE=RelWithAssert   -DUSE_GNU_PARALLEL=OFF" USE_BOOST=OFF
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8-multilib
      # clang build
    - env: CMAKE_CC="clang"   CMAKE_CXX="clang++" CMAKE_FLAGS="-Wno-sign-conversion" CMAKE_ARGS="-DCMAKE_BUILD_TYPE=RelWithAssert -DUSE_GNU_PARALLEL=OFF"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.9
          packages:
            - clang-3.9

before_script:
  # run on ramdisk
  - echo "disk=/tmp/stxxl.###.tmp,2G,syscall unlink" > ~/.stxxl
  - df -h

  - mkdir build
  - cd build
  - cmake -DCMAKE_C_COMPILER=$CMAKE_CC -DCMAKE_CXX_COMPILER=$CMAKE_CXX
    -DSTXXL_BUILD_TESTS=ON -DSTXXL_TRY_COMPILE_HEADERS=ON
    -DUSE_BOOST=$USE_BOOST $CMAKE_ARGS ../
    -DCMAKE_C_FLAGS="$CMAKE_FLAGS" -DCMAKE_CXX_FLAGS="$CMAKE_FLAGS"
    #-DCMAKE_C_FLAGS="-Wconversion $CMAKE_FLAGS" -DCMAKE_CXX_FLAGS="-Wconversion $CMAKE_FLAGS"

script:
  - make && ./tools/stxxl_tool info && ctest -V
