language: cpp
dist: trusty
sudo: required

env:
  global:
    # limit parallel threads (default is 32!)
    - OMP_NUM_THREADS=4
    - TMPDIR=/dev/shm/
    - STXXL_TMPDIR=$TMPDIR

matrix:
  include:
  # gcc-5 builds
    - env: CMAKE_CC="gcc-5" CMAKE_CXX="g++-5" CMAKE_FLAGS=""     CMAKE_ARGS="-DCMAKE_BUILD_TYPE=Release -DUSE_OPENMP=ON"
      addons: &gcc5
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5

  # gcc-7 builds
    - env: CMAKE_CC="gcc-7" CMAKE_CXX="g++-7" CMAKE_FLAGS=""     CMAKE_ARGS="-DCMAKE_BUILD_TYPE=Release -DUSE_OPENMP=ON"
      addons: &gcc7
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
    - env: CMAKE_CC="gcc-7" CMAKE_CXX="g++-7" CMAKE_FLAGS=""     CMAKE_ARGS="-DCMAKE_BUILD_TYPE=Release -DUSE_OPENMP=OFF"
      addons: *gcc7
    - env: CMAKE_CC="gcc-7" CMAKE_CXX="g++-7" CMAKE_FLAGS=""     CMAKE_ARGS="-DCMAKE_BUILD_TYPE=RelWithAssert -DUSE_OPENMP=ON"
      addons: *gcc7
    - env: CMAKE_CC="gcc-7" CMAKE_CXX="g++-7" CMAKE_FLAGS=""     CMAKE_ARGS="-DCMAKE_BUILD_TYPE=RelWithAssert -DUSE_OPENMP=OFF"
      addons: *gcc7

  # clang build
    - env: CMAKE_CC="clang-3.9"   CMAKE_CXX="clang++-3.9" CMAKE_FLAGS="" CMAKE_ARGS="-DCMAKE_BUILD_TYPE=RelWithAssert"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.9
          packages:
            - clang-3.9
            - g++-5
            - libiomp-dev
    - env: CMAKE_CC="clang-5.0"   CMAKE_CXX="clang++-5.0" CMAKE_FLAGS="" CMAKE_ARGS="-DCMAKE_BUILD_TYPE=RelWithAssert"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - g++-5
            - libiomp-dev

before_script:
  # print out some version numbers
  - $CMAKE_CXX --version
  - cmake --version

  - df -h
  # checkout foxxll and tlx
  - git submodule update --init --recursive --recommend-shallow

  - mkdir build
  - cd build
  - cmake -DCMAKE_C_COMPILER=$CMAKE_CC -DCMAKE_CXX_COMPILER=$CMAKE_CXX
    -DSTXXL_BUILD_TESTS=ON -DSTXXL_TRY_COMPILE_HEADERS=ON
    $CMAKE_ARGS ../
    -DCMAKE_C_FLAGS="$CMAKE_FLAGS" -DCMAKE_CXX_FLAGS="$CMAKE_FLAGS"

script:
- ../.travis-run.sh

